---
version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db 
    environment:
      MYSQL_DATABASE: 'dbschema'
      MYSQL_ROOT_PASSWORD: 'trontron'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  spring-boot:
    container_name: spring-boot
    build:
      context: ./pass
      dockerfile: Dockerfile
    expose:
      - "8080"
    depends_on:
      - db
      - angular
     
  angular:
    container_name: angular  
    build:
      context: ./ng-pass-crud
      dockerfile: Dockerfile
    ports:
      - "80:80"
      
volumes:
  db-data:
...  